export const REASON_CONFIGS = {
  suspended: [
    "Minor Terms of Service Violation",
    "Inappropriate Language / Conduct",
    "Spamming Activities (Warning)",
    "Temporary Investigation",
    "Behavioral Warning",
    "Unusual Activity Detected",
    "Other",
  ],
  banned: [
    "Severe Hate Speech or Harassment",
    "Fraudulent Activities / Scamming",
    "Explicit or Illegal Content",
    "Multiple Repeat Violations",
    "Fake Account / Impersonation",
    "Compromised Account (Safety)",
    "Serious Violation of Terms",
    "Other",
  ],
  active: [
    "Identity Verified Successfully",
    "Warning Issued & Acknowledged",
    "Misunderstanding / Error Cleared",
    "Evidence Provided by User",
    "Investigation Concluded",
    "Manual Review Approval",
    "Good Behavior / Appeal Accepted",
    "Other",
  ],
  unbanned: [
    "Appealed successfully",
    "First-time offender (Warning given)",
    "Mistakenly flagged by automated system",
    "Behavior improved / Probation period over",
    "Other",
  ],
  unsuspended: [
    "Appeal accepted",
    "Warning acknowledged by user",
    "Investigation completed - No violation",
    "Suspension period served early (Manual override)",
    "Other",
  ],
};
